/**
 * Regenerates the SDK from the API's own contract: builds the Fastify app
 * in-process, captures the OpenAPI document it serves, and emits typed
 * bindings. No network, no running server — the spec can never drift from
 * the code that produced it.
 *
 * Run `pnpm --filter @harbinger/sdk generate` after changing API routes,
 * then commit openapi.json and src/schema.ts together.
 *
 * This package pins typescript 5: openapi-typescript drives the classic
 * TypeScript compiler API, which the native TS 7 package no longer ships.
 */
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";
import { buildApp } from "@harbinger/api";

const app = await buildApp();
const res = await app.inject({ method: "GET", url: "/docs/json" });
if (res.statusCode !== 200) {
    throw new Error(`Fetching the OpenAPI document failed: ${res.statusCode}`);
}
await app.close();

const spec = JSON.stringify(res.json(), null, 4);
const specPath = fileURLToPath(new URL("../openapi.json", import.meta.url));
await writeFile(specPath, spec + "\n");

const header = "// Generated by scripts/generate.ts — do not edit by hand.\n";
const ast = await openapiTS(new URL("../openapi.json", import.meta.url));
const schemaPath = fileURLToPath(new URL("../src/schema.ts", import.meta.url));
await writeFile(schemaPath, header + astToString(ast));

console.log("Regenerated openapi.json and src/schema.ts");
